services:
  - type: web
    name: plant-disease-solutions
    env: node
    plan: free
    buildCommand: 'npm install'
    startCommand: 'node server.js'
    envVars:
      - key: DB_HOST
        value: your_database_host
      - key: DB_USER
        value: your_database_user
      - key: DB_PASSWORD
        value: your_database_password
      - key: DB_NAME
        value: plant_disease_solutions