name: Backend CI

on:
  push:
    branches: [ main ]
    paths:
      - 'Backend/**'
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout main repo
        uses: actions/checkout@v3

      - name: Checkout backend repo
        uses: actions/checkout@v3
        with:
          repository: poornamadhusith/GG_app_backend
          token: ${{ secrets.GITHUB_TOKEN }}
          path: GG_app_backend
          
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          
      - name: Install Dependencies
        run: |
          cd GG_app_backend
          npm install
          
      - name: Deploy to Vercel
        uses: amondnet/vercel-action@v20
        with:
          vercel-token: ${{ secrets.VERCEL_TOKEN }}
          vercel-project-id: ${{ secrets.VERCEL_PROJECT_ID }}
          working-directory: ./GG_app_backend