name: Backend CI

on:
  push:
    branches: [ main ]
    paths:
      - 'Backend/**'
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Debug step to check if the GitHub token is available
      - name: Debug GitHub Token Access
        run: echo "GitHub Token is Set"
        env:
          GH_PAT: ${{ secrets.GH_PAT }}

      # Checkout the main repository (GG_app_backend repo itself)
      - name: Checkout Main Repository
        uses: actions/checkout@v3

      # Checkout the Backend Repository using GH_PAT
      - name: Checkout Backend Repository
        uses: actions/checkout@v3
        with:
          repository: poornamadhusith/gg-mobileapp-backend
          ref: main  # Ensure correct branch is used
          token: ${{ secrets.GH_PAT }}  # Uses the secret token
          path: GG_app_backend

      # Alternative: Manually Clone Repository (Use this only if checkout fails)
      # - name: Manually Clone Backend Repo
      #   run: |
      #     git clone https://poornamadhusith:${{ secrets.GH_PAT }}@github.com/poornamadhusith/gg-mobileapp-backend.git GG_app_backend

      # Setup Node.js version 18
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      # Install Dependencies
      - name: Install Dependencies
        run: |
          cd GG_app_backend
          npm install

      # Deploy to Vercel using Secrets
      - name: Deploy to Vercel
        uses: amondnet/vercel-action@v20
        with:
          vercel-token: ${{ secrets.VERCEL_TOKEN }}
          vercel-project-id: ${{ secrets.VERCEL_PROJECT_ID }}
          working-directory: ./GG_app_backend
